### ISSUE TITLE
Remove CloudCV Website section

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/GCI#10]
Since we will not be working on `CloudCV project` during this GCI. Hence we would like to update the new website by removing this section from the existing website running at [http://gci.cloudcv.org/]( http://gci.cloudcv.org/).
<img width="1440" alt="screenshot 2018-10-08 at 3 32 24 pm" src="https://user-images.githubusercontent.com/12206047/46629589-6557c900-cb0f-11e8-87a6-be44c405185a.png">

**Comment by mad-learner** [comment]
what exactly you need

**Comment by mad-learner** [comment]
do you have  a new website.

**Comment by RishabhJain2018** [comment]
I have updated the description.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 If I remove the CloudCV Website section, do we have to change the colour scheme of the bottom sections as well.

**Comment by RishabhJain2018** [comment]
yes! It will be alternate white & blue from the Home section.
