### ISSUE TITLE
Update GCI according to 2019

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/GCI#25]
The GCI website needs to be updated with the latest additions (2019 mentors and finalists) and mentioning the EvalAI-ngx and EvalAI-CLI repos.
@RishabhJain2018

**Comment by gautamjajoo** [comment]
Yes it has to be updated. Go ahead!

**Comment by RishabhJain2018** [comment]
Hi @nikochiko, Thanks for opening the issue. We would definitely like to update the website. Would you like to help with it? 
cc: @vkartik97

**Comment by vkartik97** [comment]
This will involve
- Archiving GCI 2018 Website, just like GCI 2017 Site.
- Adding Mentor and Org Manager details from: [GCI/CloudCV Members](https://docs.google.com/spreadsheets/d/1F2zlN2q-lSrM2RSDe6VOEFFlrvpBM1UBzDjBEh9PMvQ/edit#gid=0)
- Add Winners, Runner Up and Finalists from [Code-In/Winners](https://codein.withgoogle.com/#winners)

Some details are missing. You can use placeholders for that. For image placeholder, http://gci.cloudcv.org/pics/user.png can be used.
cc: @RishabhJain2018

**Comment by nikochiko** [comment]
I would love to work on it :)
@vkartik97 Thanks for the content details. I will update accordingly.

**Comment by RishabhJain2018** [comment]
Perfect! Thanks @vkartik97 and @nikochiko for helping with it.
